qrencode: update stable
The homepage for `qrencode` no longer links to tarball files and
previous files appear to have been removed in the process, so the
`stable` URL now returns a 404 (Not Found) response. The homepage
instructs users to download source packages from the GitHub releases
page instead.

This updates the formula to use the newest tag tarball from GitHub
(4.1.1, from 2020-09-28) and adjusts the build steps/dependencies
accordingly. While building the formula, I encountered a
`qrencode.c:932:9: error: use of undeclared identifier 'VERSION'`
error during the `make` step. Looking at `configure.ac`, it appears
that `VERSION` is not set like `MAJOR_VERSION`, etc. I've included a
patch that adds this change and the formula builds as expected after
applying it.